### ISSUE TITLE
PyBadge no attribute '_joystick_X_'

### ISSUE THREAD

**Issue by GradeSchool** [adafruit/Adafruit_CircuitPython_CursorControl#11]
I've tried all the examples at https://github.com/adafruit/Adafruit_CircuitPython_CursorControl. I always get the same error- File "adafruit_cursorcontrol/cursorcontrol_cursormanager.py", line 54, in init
AttributeError: 'CursorManager' object has no attribute '_joystick_x'

Trying with a PyBadge, circuitpython 4.1, I've checked that the libraries are all installed... :(

**Comment by brentru** [comment]
@GradeSchool  I submitted a pull request fixing this issue here: https://github.com/adafruit/Adafruit_CircuitPython_CursorControl/pull/12

Does this work with your PyBadge? Are you still having the issue?
