### ISSUE TITLE
Pylint 2.x doesn't like passing object into class

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_CircuitPython_CursorControl#16]
Pylint 2.x says this:
```
************* Module adafruit_cursorcontrol.cursorcontrol
adafruit_cursorcontrol/cursorcontrol.py:46:0: R0205: Class 'Cursor' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
```
The line referenced:
https://github.com/adafruit/Adafruit_CircuitPython_CursorControl/blob/787b7cf1221b10ca603fd1cdb37f419deebf045d/adafruit_cursorcontrol/cursorcontrol.py#L45

I'm not sure why object is passed in, but I'm interested to find out why it was done.

Referencing main issue: adafruit/Adafruit_CircuitPython_Bundle#232

**Comment by evaherrada** [comment]
@kattni

**Comment by brentru** [comment]
@dherrada  I could remove and test this later today if you want to assign me to it?

**Comment by evaherrada** [comment]
@brentru Ya, that'd be great. Thanks

**Comment by tannewt** [comment]
Note, subclassing from (object) is a Python 2 thing and not needed in 3 (as the lint says). It should work exactly the same without it.
