### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_CursorControl#31]
1. Fix Cursor class docstring to include information about `bmp` parameter in `cursorcontrol.py`
2. Add typing to `bmp` parameter to `cursor_bitmap` setter method docstring in `cursorcontrol.py`
3. Add `bmp` parameter to `generate_cursor()` method docstring in `cursorcontrol.py`
4. Update `cursor` parameter type to `Cursor` in `CursorManager` class docstring in `cursorcontrol_cursormanager.py`
5. Remove `event` parameter from `_store_button_states()` method docstring in `cursorcontrol_cursormanager.py`
6. Update `cursor` parameter type to `Cursor` in `DebouncedCursorManager` class docstring in `cursorcontrol_cursormanager.py`

**Comment by FoamyGuy** [comment]
closed by #30
