### ISSUE TITLE
TypeError: unsupported bitmap type

### ISSUE THREAD

**Issue by codepope** [adafruit/Adafruit_CircuitPython_CursorControl#8]
Just trying out the examples from the Adafruit article and almost immediatly got an error:

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "adafruit_cursorcontrol/cursorcontrol.py", line 81, in init
  File "adafruit_cursorcontrol/cursorcontrol.py", line 240, in generate_cursor
TypeError: unsupported bitmap type
```

Not attempting to set a cursor bitmap. So was confused.

Sommersoft on Discord suggested a fix, swapping line 81 for

```
self.generate_cursor(self.cursor_bitmap)
````

This does resolve the issue for me.

**Comment by brentru** [comment]
@codepope Thanks for pointing this out, it was modified when we allowed user-defined cursor bitmaps. I submitted a pull request with a patch fixing this.

**Comment by brentru** [comment]
Merged into `master` and released. Closing...
